# Generated by Django 5.0.1 on 2024-02-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='adress',
            new_name='address',
        ),
    ]
